apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-workshop-sample
  github.com/project-slug: NetManagement/backstage-workshop-sample
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
